name: DEV Deployment

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    uses: ./.github/workflows/reusable.yml
    with:
      environment: dev
      github_environment: DEV
    secrets:
      SF_DEV_AUTH_URL: ${{ secrets.SF_DEV_AUTH_URL }}
      GH_PAT: ${{ secrets.GH_PAT }}
