name: DEV Deployment

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    uses: ./.github/workflows/reusable.yml
    with:
      environment: dev
    secrets:
      SF_DEV_AUTH_URL: ${{ secrets.SF_DEV_AUTH_URL }}
      SF_INT_AUTH_URL: ${{ secrets.SF_INT_AUTH_URL }}
      SF_PROD_AUTH_URL: ${{ secrets.SF_PROD_AUTH_URL }}
