name: INT Deployment

on:
  push:
    branches:
      - int

jobs:
  deploy-int:
    uses: ./.github/workflows/reusable.yml
    with:
      environment: int
      github_environment: INT
    secrets:
      SF_INT_AUTH_URL: ${{ secrets.SF_INT_AUTH_URL }}
      GH_PAT: ${{ secrets.GH_PAT }}
