name: PR Validation

on:
  pull_request:
    branches:
      - dev
      - int
      - main

jobs:
  validate-salesforce:
    uses: ./.github/workflows/reusable.yml
    with:
      environment: ${{ github.base_ref }}
    secrets:
      SF_DEV_AUTH_URL: ${{ secrets.SF_DEV_AUTH_URL }}
      SF_INT_AUTH_URL: ${{ secrets.SF_INT_AUTH_URL }}
      SF_PROD_AUTH_URL: ${{ secrets.SF_PROD_AUTH_URL }}
