name: PROD Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    uses: ./.github/workflows/reusable.yml
    with:
      environment: main
    secrets:
      SF_PROD_AUTH_URL: ${{ secrets.SF_PROD_AUTH_URL }}
      GH_PAT: ${{ secrets.GH_PAT }}
