name: Reusable Salesforce Pipeline

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Verify Salesforce CLI
        run: sf --version

      - name: Create Auth File
        shell: bash
        env:
          SF_DEV_AUTH_URL: ${{ secrets.SF_DEV_AUTH_URL }}
          SF_INT_AUTH_URL: ${{ secrets.SF_INT_AUTH_URL }}
          SF_PROD_AUTH_URL: ${{ secrets.SF_PROD_AUTH_URL }}
        run: |
          if [ "${{ inputs.environment }}" = "dev" ]; then
            echo "$SF_DEV_AUTH_URL" > auth.txt
          elif [ "${{ inputs.environment }}" = "int" ]; then
            echo "$SF_INT_AUTH_URL" > auth.txt
          elif [ "${{ inputs.environment }}" = "main" ]; then
            echo "$SF_PROD_AUTH_URL" > auth.txt
          fi

      - name: Check Auth File
        run: |
          ls -l auth.txt
          wc -c auth.txt

      - name: Authenticate Salesforce Org
        run: |
          sf org login sfdx-url --sfdx-url-file auth.txt --alias target-org

      - name: Verify Authentication
        run: |
          sf org display --target-org target-org
      - name: Debug Auth Content
        run: |
          echo "First 30 chars:"
          head -c 30 auth.txt
          echo
          echo "Last 30 chars:"
          tail -c 30 auth.txt
          echo

      - name: Install SFDX Git Delta
        run: |
          echo y | sf plugins install sfdx-git-delta

      - name: Generate Delta Package
        run: |
          mkdir -p delta

          sf sgd source delta \
            --from HEAD~1 \
            --to HEAD \
            --output-dir delta

      - name: Display Delta Files
        run: |
          ls -R delta || true

      - name: Upload Delta Package
        uses: actions/upload-artifact@v4
        with:
          name: delta-package
          path: delta
