name: Toolchain Test

on:
  workflow_dispatch:

jobs:
  toolchain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli

      - name: Verify Salesforce CLI
        run: |
          sf --version

      - name: Install SFDX Git Delta
        run: |
          echo y | sf plugins install sfdx-git-delta

      - name: Verify SFDX Git Delta
        run: |
          sf plugins | grep sfdx-git-delta || true

      - name: Install Salesforce Code Analyzer
        run: |
